"""beamtimehero — generic BL15-2 CLI.

Surfaces the tool catalog to humans and to LLM agents over claude-code's
Bash tool. Single binary, scope-segmented:

    beamtimehero ref         — bundled reference docs
    beamtimehero tool        — non-SPEC tools (data, logs, analysis, plots, file I/O)
    beamtimehero db          — action-log queries
    beamtimehero spec-read   — SPEC-bound reads (motor positions, beam status, scan #)
    beamtimehero spec-write  — SPEC-bound mutations. Every leaf requires --justification.

Discover via `--help` at any depth. `tool` / `spec-read` / `spec-write` /
`db` leaves are autogenerated from `tool_catalog.TOOL_DEFINITIONS`. `ref` is
hand-wired and pulls from `beamtimehero_cli.refdocs`.

Errors → JSON `{"ok": false, "error": "..."}` on stdout, non-zero exit.
Successful tool calls print the tool's stdout (image paths included) and exit 0.
"""
from __future__ import annotations

import argparse
import io
import json
import os
import sys
import time
import traceback
from pathlib import Path

from beamtimehero_cli import refdocs
from beamtimehero_cli.tool_catalog import TOOL_DEFINITIONS, execute_tool
from beamtimehero_cli.tool_catalog.lineage import TOOL_LINEAGE


# ---------------------------------------------------------------------------
# Categorization
# ---------------------------------------------------------------------------
# Four trees + ref. Categorization is data-driven from TOOL_LINEAGE and the
# tool definition's required arguments.

CATEGORY_OVERRIDES: dict[str, str] = {}


def categorize(tool_def: dict) -> str:
    name = tool_def["function"]["name"]
    if name in CATEGORY_OVERRIDES:
        return CATEGORY_OVERRIDES[name]
    lineage = TOOL_LINEAGE.get(name) or {}
    if lineage.get("source") == "autonomy_db":
        return "db"
    params = tool_def["function"].get("parameters", {}) or {}
    required = set(params.get("required", []) or [])
    if "justification" in required:
        return "spec-write"
    spec_cmd_name = lineage.get("spec_command")
    if spec_cmd_name is not None:
        return "spec-read"
    return "tool"


# ---------------------------------------------------------------------------
# JSON-schema → argparse mapping
# ---------------------------------------------------------------------------

_BOOL_TRUE = {"true", "yes", "on", "1"}
_BOOL_FALSE = {"false", "no", "off", "0"}


def _bool_from_str(s: str) -> bool:
    sl = s.strip().lower()
    if sl in _BOOL_TRUE:
        return True
    if sl in _BOOL_FALSE:
        return False
    raise argparse.ArgumentTypeError(f"expected boolean (true/false), got {s!r}")


def _json_arg(s: str):
    try:
        return json.loads(s)
    except json.JSONDecodeError as e:
        raise argparse.ArgumentTypeError(f"expected JSON, got {s!r}: {e}") from e


def add_arg(p: argparse.ArgumentParser, key: str, prop: dict, required: bool) -> None:
    flag = f"--{key.replace('_', '-')}"
    desc = (prop.get("description") or "").strip()
    kwargs: dict = {"help": desc}
    if "default" in prop:
        kwargs["default"] = prop["default"]
    if required:
        kwargs["required"] = True

    enum = prop.get("enum")
    if enum:
        kwargs["choices"] = [str(v) for v in enum]
        p.add_argument(flag, **kwargs)
        return

    t = prop.get("type", "string")
    if t == "integer":
        kwargs["type"] = int
        p.add_argument(flag, **kwargs)
    elif t == "number":
        kwargs["type"] = float
        p.add_argument(flag, **kwargs)
    elif t == "boolean":
        kwargs["type"] = _bool_from_str
        kwargs["metavar"] = "BOOL"
        p.add_argument(flag, **kwargs)
    elif t in ("array", "object"):
        kwargs["type"] = _json_arg
        kwargs["metavar"] = "JSON"
        p.add_argument(flag, **kwargs)
    else:
        p.add_argument(flag, **kwargs)


# ---------------------------------------------------------------------------
# Build the parser
# ---------------------------------------------------------------------------


class ToolParser(argparse.ArgumentParser):
    def error(self, message: str) -> None:  # type: ignore[override]
        payload: dict = {"ok": False, "error": f"argparse: {message}"}
        print(json.dumps(payload))
        sys.exit(2)


def build_ref_subtree(subs: argparse._SubParsersAction) -> None:
    ref = subs.add_parser(
        "ref",
        help="Reference docs (use `ref --list` to enumerate, `ref <name>` to fetch).",
    )
    ref.add_argument("doc_name", nargs="?", help="Reference document name.")
    ref.add_argument(
        "--list", action="store_true", dest="list_docs",
        help="List all available reference documents.",
    )


def build_catalog_subtrees(
    subs: argparse._SubParsersAction,
    tool_defs: list[dict],
) -> None:
    tool_tree = subs.add_parser(
        "tool",
        help="Non-SPEC tools: data queries, analysis, plotting, file I/O.",
    )
    db_tree = subs.add_parser(
        "db",
        help="Action-log queries.",
    )
    spec_read_tree = subs.add_parser(
        "spec-read",
        help="SPEC-bound reads (motor positions, beam status). No mutation.",
    )
    spec_write_tree = subs.add_parser(
        "spec-write",
        help="SPEC-bound mutations. Every leaf requires --justification.",
    )

    bucket = {
        "tool": tool_tree.add_subparsers(dest="leaf", metavar="<command>"),
        "db": db_tree.add_subparsers(dest="leaf", metavar="<command>"),
        "spec-read": spec_read_tree.add_subparsers(dest="leaf", metavar="<command>"),
        "spec-write": spec_write_tree.add_subparsers(dest="leaf", metavar="<command>"),
    }

    for tdef in tool_defs:
        fn = tdef.get("function") or {}
        name = fn.get("name")
        if not name:
            continue
        category = categorize(tdef)
        params = fn.get("parameters") or {}
        properties = params.get("properties") or {}
        required = set(params.get("required") or [])
        description = (fn.get("description") or "").strip()

        cli_name = name.replace("_", "-")
        leaf = bucket[category].add_parser(cli_name, help=description)
        leaf.set_defaults(_tool_name=name, _tool_category=category)
        for key, prop in properties.items():
            add_arg(leaf, key, prop or {}, key in required)


def build_parser() -> argparse.ArgumentParser:
    parser = ToolParser(
        prog="beamtimehero",
        description=(
            "Unified beamline CLI. Discover trees with `beamtimehero --help`; "
            "leaves with `beamtimehero <tree> <cmd> --help`."
        ),
    )
    trees = parser.add_subparsers(dest="tree", metavar="<tree>")

    build_ref_subtree(trees)
    build_catalog_subtrees(trees, TOOL_DEFINITIONS)
    return parser


# ---------------------------------------------------------------------------
# Subcommand dispatch
# ---------------------------------------------------------------------------

def _print_doc_index() -> int:
    lines = ["Available reference documents:", ""]
    for name, desc in refdocs.list_docs():
        lines.append(f"  {name:25s} {desc}")
    lines.append("")
    lines.append("Usage: beamtimehero ref <doc-name>")
    print("\n".join(lines))
    return 0


def run_ref(args: argparse.Namespace) -> int:
    if args.list_docs or not args.doc_name:
        return _print_doc_index()
    name = args.doc_name
    if not refdocs.has_doc(name):
        print(json.dumps({
            "ok": False,
            "error": (f"unknown reference '{name}'. "
                      f"Run `beamtimehero ref --list` to see available docs."),
        }))
        return 1
    try:
        print(refdocs.get_doc(name))
        return 0
    except FileNotFoundError:
        print(json.dumps({
            "ok": False,
            "error": f"reference file not found for '{name}'",
        }))
        return 1


def run_tool_leaf(args: argparse.Namespace) -> int:
    name = args._tool_name
    framework_keys = {"tree", "leaf", "_tool_name", "_tool_category"}
    payload: dict = {}
    for k, v in vars(args).items():
        if k in framework_keys or v is None:
            continue
        payload[k] = v

    try:
        text, images = execute_tool(name, payload)
    except Exception as e:  # noqa: BLE001
        traceback.print_exc(file=sys.stderr)
        print(json.dumps({"ok": False, "error": str(e)}, default=str))
        return 1

    if images:
        try:
            import base64
            from datetime import datetime
            out_dir = Path(os.environ.get("BEAMTIMEHERO_PLOTS_DIR")
                           or (Path.cwd() / "data" / "tool_plots"))
            out_dir.mkdir(parents=True, exist_ok=True)
            paths: list[str] = []
            datafile_stem: str | None = None
            scan_number_str: str | None = None
            if name == "plot_scan":
                fn_arg = payload.get("file_name")
                sn_arg = payload.get("scan_number")
                if fn_arg and sn_arg is not None:
                    try:
                        datafile_stem = Path(str(fn_arg)).stem or None
                        scan_number_str = str(int(sn_arg))
                    except (TypeError, ValueError):
                        pass
            for i, b64 in enumerate(images):
                ts = f"{datetime.now():%Y%m%d_%H%M%S_%f}"
                if datafile_stem and scan_number_str is not None:
                    fname = f"plot_scan_{datafile_stem}_scan{scan_number_str}_{ts}_{i}.png"
                else:
                    fname = f"{name}_{ts}_{i}.png"
                fn = out_dir / fname
                fn.write_bytes(base64.b64decode(b64))
                paths.append(str(fn))
            payload_out = {
                "text": text,
                "plot_path": paths[0] if paths else None,
                "image_paths": paths,
            }
            print(json.dumps(payload_out, default=str))
            return 0
        except Exception as e:  # noqa: BLE001
            print(json.dumps({"text": text, "image_error": str(e)}, default=str))
            return 0

    print(text if isinstance(text, str) else json.dumps(text, default=str))
    return 0


_KNOWN_TREES = frozenset({"ref", "tool", "db", "spec-read", "spec-write"})


# ---------------------------------------------------------------------------
# stdout tee — capture what the CLI prints so the cli_log can store it
# ---------------------------------------------------------------------------

class TeeStdout(io.TextIOBase):
    """Forward writes to the real stdout AND a capture buffer (bounded tail)."""

    def __init__(self, real, max_bytes: int) -> None:
        self._real = real
        self._buf = io.StringIO()
        self._max = max_bytes

    def write(self, s):  # noqa: D401
        self._real.write(s)
        self._buf.write(s)
        cur = self._buf.getvalue()
        if len(cur) > self._max * 2:
            self._buf = io.StringIO()
            self._buf.write(cur[-self._max:])
        return len(s)

    def flush(self):
        self._real.flush()

    def captured(self) -> str:
        s = self._buf.getvalue()
        return s[-self._max:] if len(s) > self._max else s

    def isatty(self):
        try:
            return self._real.isatty()
        except Exception:
            return False


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def dispatch(parser: argparse.ArgumentParser, args: argparse.Namespace) -> int:
    if not getattr(args, "tree", None):
        parser.print_help()
        return 0
    if args.tree == "ref":
        return run_ref(args)
    if not getattr(args, "leaf", None):
        parser.parse_args([args.tree, "--help"])
        return 0
    return run_tool_leaf(args)


def run_with(
    parser_builder,
    dispatcher,
    argv: list[str] | None = None,
    *,
    known_trees: frozenset[str] | None = None,
) -> int:
    """Wrap parser-build + parse + dispatch with stdout tee + CLI logging.

    Used by `main()` directly and by consumers (e.g. the autonomous repo)
    that compose their own parser and dispatcher on top of the upstream
    helpers. Same stdout-tee tail capture and `record_cli_invocation`
    fallback behavior the standalone `main()` provides.

    `known_trees` is the set of tree names the fallback path uses to
    classify `argv[0]` when an early SystemExit (e.g. `--help`) fires
    before the Namespace is built. Defaults to the upstream set.
    """
    raw_argv = list(sys.argv[1:]) if argv is None else list(argv)
    known = known_trees if known_trees is not None else _KNOWN_TREES

    try:
        from beamtimehero_cli.config import CLI_LOG_ENABLED, CLI_LOG_MAX_RESULT_BYTES, SPEC_MOCK
        log_enabled = CLI_LOG_ENABLED
        max_bytes = CLI_LOG_MAX_RESULT_BYTES
        spec_mock_flag = 1 if SPEC_MOCK else 0
    except Exception:
        log_enabled = False
        max_bytes = 65536
        spec_mock_flag = None

    if not log_enabled:
        parser = parser_builder()
        args = parser.parse_args(argv)
        return dispatcher(parser, args)

    started = time.monotonic()
    real_stdout = sys.stdout
    tee = TeeStdout(real_stdout, max_bytes)
    sys.stdout = tee

    parsed: argparse.Namespace | None = None
    rc = 0
    error_message: str | None = None
    try:
        try:
            parser = parser_builder()
            parsed = parser.parse_args(argv)
            rc = dispatcher(parser, parsed)
        except SystemExit as e:
            rc = int(e.code) if isinstance(e.code, int) else (0 if e.code is None else 1)
            raise
        except Exception as e:  # noqa: BLE001
            rc = 1
            error_message = f"{type(e).__name__}: {e}"
            raise
    finally:
        sys.stdout = real_stdout
        latency_ms = int((time.monotonic() - started) * 1000)
        try:
            from beamtimehero_cli.action_log.cli_log import record_cli_invocation
            tree_hint = raw_argv[0] if raw_argv and raw_argv[0] in known else None
            tree = getattr(parsed, "tree", None) if parsed is not None else tree_hint
            leaf = getattr(parsed, "leaf", None) if parsed is not None else None
            tool_name = getattr(parsed, "_tool_name", None) if parsed is not None else None
            agent_role = getattr(parsed, "_agent_role", None) if parsed is not None else None
            justification = getattr(parsed, "justification", None) if parsed is not None else None
            record_cli_invocation(
                argv=raw_argv,
                tree=tree,
                leaf=leaf,
                tool_name=tool_name,
                agent_role=agent_role,
                justification=justification,
                exit_code=rc,
                latency_ms=latency_ms,
                stdout_tail=tee.captured() or None,
                error_message=error_message,
                spec_mock=spec_mock_flag,
            )
        except Exception:  # noqa: BLE001 — never break the CLI
            pass

    return rc


def main(argv: list[str] | None = None) -> int:
    return run_with(build_parser, dispatch, argv)


if __name__ == "__main__":
    sys.exit(main())
